### ISSUE TITLE
Minema crashes when I try to record : Can't export frame 

### ISSUE THREAD

**Issue by shiro2505** [daipenger/minema#19] opened 2020-12-27 06:42 UTC
Hi, I am on Windows 10 and I use Minema v3.5.4-ShaderSync but when I try to record it crashes

FFmpeg version is: 2020-12-24-git-9a0f5e412a-full_build

When I try to record with minema it tells me the following error:

java.util.concurrent.ExecutionException
java.lang.RuntimeException: Can't export frame 1
Cause:
java.lang.RuntimeException
Can't export frame 1
See log for full stacktrace
this is the log:
https://pastebin.com/v1VJNhha

**Comment by mchorse** [comment] 2020-12-27 09:11
Try using this build of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z).

**Comment by shiro2505** [comment] 2020-12-27 19:11
> Try using this build of [ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z).

It did not work, here is the complete log:
https://pastebin.com/QQSi1g2H

**Comment by mchorse** [comment] 2020-12-27 19:12
@shiro2505 can you provide an ffmpeg log? It should be in the Capture path folder, one of the log files.

**Comment by shiro2505** [comment] 2020-12-27 19:14
@mchorse here is a recent log
[2020-12-27_15.08.17.log](https://github.com/daipenger/minema/files/5745049/2020-12-27_15.08.17.log)

**Comment by mchorse** [comment] 2020-12-27 19:17
Did you edit by any chance the Encoding > Encoder arguments option? If no, try resetting it to default state (there is one of the buttons on the right that allows to reset the value), and try again.

**Comment by shiro2505** [comment] 2020-12-27 19:22
![screenshot](https://user-images.githubusercontent.com/73242981/103178222-4ad8aa00-4857-11eb-884b-fb2be8e7147c.png)
just modify the location of ffmpeg

**Comment by mchorse** [comment] 2020-12-27 19:42
Hm... this is so weird... I'm not really sure what could be the problem. It's certainly not a permission error, as the log files and the fact that ffmpeg log exists shows that. What is your Frame width and Frame height in Capturing settings (maybe just send `.minecraft/config/minema.cfg`)?

**Comment by shiro2505** [comment] 2020-12-27 19:46
the frame height is 1440 and frame width is 900

**Comment by shiro2505** [comment] 2020-12-27 19:49
this is minema's configuration file

[minema.zip](https://github.com/daipenger/minema/files/5745091/minema.zip)

**Comment by mchorse** [comment] 2020-12-27 19:56
Everything seems fine, my last suggestion would be create a new folder within `C:\ffmpeg\` and call it something like `movies`, and change the Capture path in Capturing option to `C:\ffmpeg\movies\`. Try recording afterwards.

**Comment by shiro2505** [comment] 2020-12-27 19:59
the error continues ☹

**Comment by mchorse** [comment] 2020-12-27 20:03
Are you sure that the Capture path saved? I.e. you can't exit the menu by pressing Escape, you have to close it using Done button until you exit to Mods Option screen. If you did save, then I have sadly no idea... 😔

You could also try testing whether the problem is with ffmpeg, by opening Command Prompt and executing `C:\ffmpeg\bin\ffmpeg.exe`. If the output is something like:

> ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 9.1.1 (GCC) 20190807
>   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Hyper fast Audio and Video encoder
> usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
> 
> Use -h to get full help or, even better, run 'man ffmpeg'

Then everything is alright with ffmpeg.

**Comment by shiro2505** [comment] 2020-12-27 20:09
ffmpeg version 4.3.1-2020-11-19-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder

**Comment by autaiaisme** [comment] 2021-01-04 23:30
Hey so I this problem may have been awhile ago but i think i figured it out because i had the same problem.... its most likely you dont have enough space on your pc so clear some memory and it should work.

**Comment by MDSpielt** [comment] 2021-02-14 15:56
Hello Guys!
I have 2 hard disks but I cannot set the export path to D) in Minema.

**Comment by mchorse** [comment] 2021-02-14 19:24
> Hello Guys!
> I have 2 hard disks but I cannot set the export path to D) in Minema.

What do you mean by "I cannot?" Can you be more specific?

**Closed as completed** 2022-12-22 15:41 UTC
